import { useEffect } from "react"
import { useRouter } from "next/router"
import type { AppProps } from "next/app"
import Head from "next/head"
import NProgress from "nprogress"

import "@/styles/nprogress.css"
import "@/styles/globals.css"

function MyApp({ Component, pageProps }: AppProps) {
  const router = useRouter()

  NProgress.configure({
    showSpinner: false,
  })

  useEffect(() => {
    const handleRouteStart = () => NProgress.start()
    const handleRouteDone = () => NProgress.done()

    router.events.on("routeChangeStart", handleRouteStart)
    router.events.on("routeChangeComplete", handleRouteDone)
    router.events.on("routeChangeError", handleRouteDone)

    return () => {
      router.events.off("routeChangeStart", handleRouteStart)
      router.events.off("routeChangeComplete", handleRouteDone)
      router.events.off("routeChangeError", handleRouteDone)
    }
  }, [router])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </div>
  )
}

export default MyApp
