name: Test

on:
  push:
    branches: [main, feature/**]
  pull_request:
    branches: [main]

  workflow_dispatch:

env:
  FORCE_COLOR: 1
  playwright_version: 1.21.1

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        node: [17]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0-rc.7
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Lint code
        run: pnpm lint
      - name: Cache Playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: cache-playwright-linux-${{ env.playwright_version }}
      - name: Install Playwright
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install --with-deps
      - name: Run jest tests
        run: pnpm test:ci
      - name: Run Playwright tests
        run: pnpm test:e2e
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report
      - name: Upload code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 75bd5ba3780bef628be78e35d58566ac4d0f6a277c6239f5551d6c52f354da26
        with:
          coverageCommand: pnpm coverage
