name: Test

on:
  push:
    branches: [main, feature/**]
  pull_request:
    branches: [main]

  workflow_dispatch:

env:
  FORCE_COLOR: 1

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        node: [17]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0-rc.7
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright
        run: pnpm exec playwright install --with-deps
      - name: Run jest tests
        run: pnpm test
      - name: Run playwright tests
        run: pnpm test:e2e
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report
